/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cadium_future_FutureStandardExecutor */

#ifndef _Included_org_cadium_future_FutureStandardExecutor
#define _Included_org_cadium_future_FutureStandardExecutor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cadium_future_FutureStandardExecutor
 * Method:    async
 * Signature: (ILorg/cadium/future/FutureTask;)V
 */
JNIEXPORT void JNICALL Java_org_cadium_future_FutureStandardExecutor_async
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_cadium_future_FutureStandardExecutor
 * Method:    collect
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_cadium_future_FutureStandardExecutor_collect
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_cadium_future_FutureStandardExecutor
 * Method:    flush
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_cadium_future_FutureStandardExecutor_flush
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_cadium_future_FutureStandardExecutor
 * Method:    wait
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_cadium_future_FutureStandardExecutor_wait
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
